import { z } from 'zod'

/**
 * docs/03 section 5.4. Generated by 3D from the asset manifest and passed into
 * Call B as the single source of truth for allowed values.
 *
 * OPEN PROPOSAL, not yet agreed by the team: `entries` gives every tag a short
 * description and its aliases, so the model is not guessing what "kiosks" looks
 * like and the enum-to-asset aliasing is machine-readable instead of living in
 * 3D's head. It is optional here on purpose - the taxonomy validates with or
 * without it, so nothing breaks while the team decides. See the note in
 * integration/ before building against it.
 */

export const taxonomyEntry = z.object({
  tag: z.string(),
  label: z.string(),
  description: z.string().max(200),
  aliases: z.array(z.string()).default([]),
})

export const assetTaxonomy = z.object({
  version: z.string(),
  enums: z.record(z.string(), z.array(z.string())),
  zoning_defaults: z.record(z.string(), z.record(z.string(), z.unknown())),
  entries: z.array(taxonomyEntry).optional(),
})

export type AssetTaxonomy = z.infer<typeof assetTaxonomy>
export type TaxonomyEntry = z.infer<typeof taxonomyEntry>
